### PR TITLE
add xxx token

### PR DESCRIPTION
**Pull request by egrassy**

### CODE REVIEW

**Comment by egrassy** [comment]
hi sir @alecande11 can u check it please?

**Comment by terencelimzhengwei** [comment]
@egrassy - why are there two images added for the xxx token? Please keep only one thank you

**Comment by terencelimzhengwei** [comment]
@egrassy - the file you uploaded is different from the image that's shown on chain (https://i.imgur.com/tVzAnyP.png). We generally do not allow for these type of discrepancies

**Comment by egrassy** [comment]
it seems to me that I have made changes everywhere where I need the images to be the same everywhere, please point me where I should make such changes
(https://i.imgur.com/Pz24fY5.png )

**Pull request merged**
