### PR TITLE
feat: disable gov on certain chains

### PR DESCRIPTION
**Pull request by ericHgorski**

### CODE REVIEW

**Comment by terencelimzhengwei** [comment]
governance spelling is wrong - and also should we adopt the name of the cosmos module (i.e. on LCD there is /staking and /gov). should we have this as "gov" instead of "governance"?

**Comment by ericHgorski** [comment]
> governance spelling is wrong - and also should we adopt the name of the cosmos module (i.e. on LCD there is /staking and /gov). should we have this as "gov" instead of "governance"?

sure!

**Comment by ericHgorski** [comment]
To be used in conjunction with: https://github.com/terra-money/station/pull/517/

**Comment by ericHgorski** [comment]
merging this in if it looks ok @terencelimzhengwei

**Review by terran6 — APPROVED** [review]

**Review by mwmerz — APPROVED** [review]

**Pull request merged**
