### PR TITLE
Add png files for BBL Logos

### PR DESCRIPTION
**Pull request by tvl83**
We noticed some images were broken because they point to .png instead of .webp so these are the .png files

Updated images to png and updated .js files for appropriate chains.

### CODE REVIEW

**Comment by terencelimzhengwei** [comment]
@tvl83 - why do we need an update to png though? webp seems to be working fine

**Comment by tvl83** [comment]
https://alliance-dashboard.terra.money/?selected=phoenix-1

has a broken image looking for the png

**Comment by tvl83** [comment]
i could keep the webp just have both formats in the repo?

**Comment by tvl83** [comment]
image was fixed on the alliance dashboard without the need of this pr

**Pull request closed without merging**
